spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    username: weatherUser
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
yahoo:
  api:
    url: https://query.yahooapis.com/v1/public/yql?{q}&format=json
    query: select * from weather.forecast where woeid = {city_id}
  nameService: yahoo